Numpy arrays

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
# NOT: a = array([1, 2, 3])
type(a)

numpy.ndarray

In [3]:
a.shape

(3,)

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

![Description](numpy.png)

How to access elements of an array (slicing)

In [5]:
a = np.array([1, 2, 3])
# how do we get the second element? Hint: think of lists!

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
# how do we get the second row?
print(a[1])
print(a[1, :])

[4 5 6]
[4 5 6]


In [13]:
# and the second column?

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[:, 1])

[[1 2 3]
 [4 5 6]]
[2 5]


In [14]:
# and how do we get the second element of the second row?

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[1,1])

5


In [16]:
a = np.arange(0, 16)
print(a)
# how do we get every other element of a?
a[::2]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [18]:
a = np.reshape(a, (4, 4))
print(a)
# how do we get the second and third elements of the second and third row?
# and if I wanted to replace them with 1?
a[1:3, 1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 5,  6],
       [ 9, 10]])

Why do we use arrays instead of lists? Using arrays usually is faster, and uses less memory

In [ ]:
# I want to add 0.5 to every element of a list. How do I do that?
a = list(range(16))
print(a)

a = [i + 0.5 for i in a]
print(a)

a = a * 2
print(a)

In [ ]:
# using an array
a = np.arange(0, 16)
print(a)

a = a + 0.5
print(a)

a = a * 2
print(a)

Some interesting functions

In [ ]:
a = np.random.rand(6)
print(a)

idx = np.argsort(a) # returns the indices that would sort the array
print(idx)
print(a[idx])

In [25]:
a = np.random.rand(6)
print(a)

max_a = np.max(a) # returns the maximum value of a
max_idx = np.argmax(a) # returns the index of the maximum value of a
print('Maximum: ', max_a, ' at index: ', max_idx)

min_a = np.min(a) # returns the minimum value of a
min_idx = np.argmin(a) # returns the index of the minimum value of a
print('Minimum: ', min_a, ' at index: ', min_idx)

[0.97033132 0.5354501  0.04563151 0.97653108 0.44057176 0.19112048]
Maximum:  0.9765310807984343  at index:  3
Minimum:  0.04563150793994153  at index:  2


In [27]:
a = np.random.rand(6)
print(a)

idx = np.where(a > 0.5)[0] # returns the indices of the elements that are greater than 0.5
print(idx)
idx[0]

[0.23893299 0.42197955 0.14441666 0.4591573  0.86477596 0.37170112]
[4]


np.int64(4)

Other relevant functions

In [34]:
a = np.random.rand(6)
print(a)

np.sum(a)

np.mean(a)

np.std(a)

np.var(a)

np.median(a)

np.percentile()


[0.17755408 0.99677322 0.99911407 0.05062648 0.73350033 0.46490433]


np.float64(0.5992023297382172)

Exercise: You are given a NumPy array representing monthly sales (in $1,000s) for a small business over 12 months. Use NumPy to perform basic analysis.
1. Calculate total and average sales
2. Find the month with the highest and lowest sales
3. List months with sales above average
4. Sort sales and show rankings

sales = np.array([23, 19, 31, 25, 29, 33, 28, 26, 35, 40, 38, 30])  # Jan to Dec

In [74]:
sales = np.array([23, 19, 31, 25, 29, 33, 28, 26, 35, 40, 38, 30])

# Total and Average Sales

print(np.sum(sales))

  # prettier

avg_sales = np.mean(sales)
print("Average sales: ", avg_sales, "thousand USD")

# Months with the max and min sales

month_max = np.argmax(sales)
month_min = np.argmin(sales)
print(month_max)
print(month_min)

# List months with sales above average
idx = np.where(sales > 29.75)
print(idx, +1)
  # Ranking sales
ranks = np.argsort(sales)
print(ranks)
print(sales[ranks])

#Alice's answer
sorted_sales = np.argsort(sales)[::-1]
print("Sorted Months: ", sorted_sales +1)

357
Average sales:  29.75 thousand USD
9
1
(array([ 2,  5,  8,  9, 10, 11]),) 1
[ 1  0  3  7  6  4 11  2  5  8 10  9]
[19 23 25 26 28 29 30 31 33 35 38 40]
Sorted Months:  [10 11  9  6  3 12  5  7  8  4  1  2]
